### ISSUE TITLE
Pretrained Weights for Bloom and BloomZ (4-bit)

### ISSUE THREAD

**Issue by agemagician** [IST-DASLab/gptq#10]
Hi,

Thanks a lot for the excellent work.

Could you share with us a pretrained weights for Bloom and BloomZ (4-bits) ?

**Comment by efrantar** [comment]
Hi, sharing such extremely large models is a bit tricky, I think simply rerunning the code is probably easier (it should work as is for `bigscience/bloom`; not sure about BLOOMZ, we haven't used that model before). In the past few months, a lot of GPTQ quantized models (produced by follow-up projects to our original paper implementation in this repository) have been uploaded to [HuggingFace](https://huggingface.co/models?search=gptq), perhaps you will find a suitable already quantized model there (e.g., [this](https://huggingface.co/TheBloke/bloomz-176B-GPTQ) looks to be 4-bit BLOOM-Z version).
