### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by jinz2014** [IST-DASLab/gptq#18]
Hello,
I tried your instruction and got a value error. Was I doing right for benchmarking ?  Thank you.

CUDA_VISIBLE_DEVICES=0 python opt.py facebook/opt-125m c4 --wbits 3 --save opt125m-3bit.pt

CUDA_VISIBLE_DEVICES=0 python opt.py facebook/opt-125m c4 --load opt125m-3bit.pt --benchmark 128
Loading model ...
Done.
Found cached dataset json (/$HOME/.cache/huggingface/datasets/allenai___json/allenai--c4-6fbe877195f42de5/0.0.0/fe5dd6ea2639a6df622901539cb550cf8797e5a6b2dd7af1cf934bed8e233e6e)
Found cached dataset json (/$HOME/.cache/huggingface/datasets/allenai___json/allenai--c4-efc3d4f4606f44bd/0.0.0/fe5dd6ea2639a6df622901539cb550cf8797e5a6b2dd7af1cf934bed8e233e6e)
Benchmarking ...
Traceback (most recent call last):
  File "/$HOME/gptq/opt.py", line 455, in <module>
  ... 
  File "/$HOM/mambaforge/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 637, in forward
    batch_size, seq_length = input_shape
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by wejoncy** [comment]
![image](https://github.com/IST-DASLab/gptq/assets/9417365/a6152f06-8f28-4480-8287-b9712301af3c)

Run into the same issue, the picture above can workaround it.

**Comment by efrantar** [comment]
I think this should now be resolved with 8eca10660e9e48e71333c1f79129a818e7926b70.
