### ISSUE TITLE
About `--sym` zero point

### ISSUE THREAD

**Issue by tpoisonooo** [IST-DASLab/gptq#19]
If <wbit=4, sym=True>,  `self.zero=8`  as implemented [here](https://github.com/IST-DASLab/gptq/blob/ff75576b05c3bb1df99f43b570528d18f9ff0e6d/quant.py#L74).

I thought `self.zero=0` according to [quantization doc](https://intellabs.github.io/distiller/algo_quantization.html) or [some inference code](https://github.com/Tencent/ncnn/blob/master/tools/quantize/ncnn2table.cpp).

Is there any standard or consensus about symmetric quantization ?

**Comment by efrantar** [comment]
We are here simulating quantization; `self.zero = 8` means that quantized values are in range [-8, 7] which should correspond to standard symmetric quantization as in the doc you linked (which e.g. shows [-128, 127] for 8-bit). In reality, 0 is still 0 during calculations, the `self.zero` is only used for number representation.
