### ISSUE TITLE
About the cuda code, I think "tmp2 >> 30" should be " tmp2 >> 31"

### ISSUE THREAD

**Issue by JachinJiang** [IST-DASLab/gptq#43]
tmp = (tmp2 >> 30) | ((tmp1 << 1) & 0x6);

to construct a 3-bit number, tmp1 contributes 2bit, why tmp2 also contributes 2bit?
I'm confused.

**Comment by efrantar** [comment]
Hi, `tmp2` was already shifted by one before in this [line](https://github.com/IST-DASLab/gptq/blob/2d65066eeb06a5c9ff5184d8cebdf33662c67faf/quant_cuda_kernel.cu#L131C5-L131C5) and thus only contributes 1 bit in this expression.

**Comment by JachinJiang** [comment]
oh, my fault, I'll close this issue, thank you.
