### ISSUE TITLE
H_inv not updated

### ISSUE THREAD

**Issue by MilesQLi** [IST-DASLab/gptq#44]
After each quantization step, H_inv should be updated, but in the code fasterquant, H_inv is not updated. Is it a bug?

**Comment by efrantar** [comment]
Hi, these updates are all precomputed in advance by the Cholesky decomposition, see also "Step 3: Cholesky Reformulation" in our paper.

**Comment by MilesQLi** [comment]
Step 3 in the paper is not specific: with no formula to show how Cholesky decomposition is used to update (5) and (4). That makes this step very hard to understand. Is there a clearer description of this part?

**Comment by MilesQLi** [comment]
I did the derivation myself.
